name: Daily Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'

permissions:
  contents: write  # Required to allow commit and push

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create daily.txt - 23f1001093@ds.study.iitm.ac.in
        run: |
          echo "Daily updates: $(date)" > daily.txt

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily.txt
          git commit -m "Daily commit: $(date)" || echo "No changes to commit"
          git push origin HEAD
